### ISSUE TITLE
Admin Panel

### ISSUE THREAD

**Issue by ydidwania** [DevCom-IITB/instiapp-api#78]
This panel should display relevant information in the `changelist`itself , and define appropriate permission levels for different users (having admin access)  to modify/create objects.

**Comment by pulsejet** [comment]
This should be possible to do as explained [here](https://stackoverflow.com/a/6312540), but we need to be a bit careful, since quoting the author,
> The Django admin design philosophy is that any user with access to the admin (is_staff==True) is a trusted user, e.g. an employee, hence the "staff" designation to even gain access to the admin. While you can customize the admin to restrict areas, allowing anyone not within your organization access to your admin is considered risky, and Django makes no guarantees about any sort of security at that point.

As far as implementation is concerned, this would probably involve refactoring lots of code since we wouldn't want duplication of code between DRF Viewsets and django admin views. Due to complexity of the authorization required, I haven't found a way yet to represent them with Django's built-in permissions model, but such a change would be welcome.

**Comment by ydidwania** [comment]
We aren't providing access to any more users than before. This is just for  ease of working with the admin. [Docs](https://docs.djangoproject.com/en/dev/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_display)

**Comment by Krishna-Baldwa** [comment]
Done
